version: '3'
name: 'otus_lessons'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - otus-network

  mysql:
    container_name: mysql_otus
    build:
      context: docker/mysql
    ports:
      - 3306:3306
    volumes:
      - './docker/mysql/volume:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=otus
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - otus-network

  php:
    build:
      context: docker/php
    environment:
      - UPLOAD_LIMIT=512M
      - DB_HOST=mysql
    volumes:
      - './src:/var/www/'
    networks:
      - otus-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=php
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=512M
    networks:
      - otus-network

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
    - './docker/redis/d–∞ta:/root/redis'
    - './docker/redis/redis.conf:/usr/local/etc/redis/redis.conf'
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - otus-network


# Docker Networks
networks:
  otus-network:
    driver: bridge