version: '3'
name: 'chubsrx'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - app-network

  mysql:
    container_name: mysql-chabs
    build:
      context: docker/mysql
    ports:
      - 3306:3306
    volumes:
      - './docker/mysql/volume:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=chabsrx
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  php:
    build:
      context: docker/php
    environment:
      - UPLOAD_LIMIT=512M
      - DB_HOST=mysql
    volumes:
      - './src:/var/www/'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=php
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=512M
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge